version: 2.1

orbs:
  node: circleci/node@5.1.0

workflows:
  testing:
    jobs:
      - nodejs-test
  # Based on the success of this job, we could then go on to build an image using the included Dockerfile and the CircleCI Docker orb, and continue to deployment...

jobs:
  nodejs-test:
    executor: node/default
    steps:
      - run: echo "Running build and test!"
      # Get the code from the repository
      - checkout
      # Write environmental variables to the .env file
      - run: echo "HTTP_USERNAME=" > .env
      - run: echo "$HTTP_USERNAME" >> .env
      - run: echo "HTTP_PASSWORD=" >> .env
      - run: echo "$HTTP_PASSWORD" >> .env
      - run: cat .env
      # Confirm Node.js is present
      - run: node --version
      # Install dependencies
      - run:
          command: npm install
          name: Install Node.js app dependencies
      # Run test
      - run:
          command: npm run test
          name: Test app
