version: 2.1

orbs:
  node: circleci/node@5.1.0

workflows:
  testing:
    jobs:
      - nodejs-test:
          # Set the contexts this job will run in - this must match the name of the context in your Organisation Settings
          context:
            - example_context
  # Based on the success of this job, we could then go on to build an image using the included Dockerfile and the CircleCI Docker orb, and continue to deployment...

jobs:
  nodejs-test:
    executor: node/default
    steps:
      - run: echo "Running build and test!"
      # Get the code from the repository
      - checkout
      # Confirm Node.js is present
      - run: node --version
      # Install dependencies
      - run:
          command: npm install
          name: Install Node.js app dependencies
      # Write environmental variables to the .env file
      - run: echo "HTTP_USERNAME=$HTTP_USERNAME" > .env
      - run: echo "HTTP_PASSWORD=$HTTP_PASSWORD" >> .env
      - run: cat .env
      # Run test
      - run:
          command: npm run test
          name: Test app
